//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TailwindTraders.Mobile.Features.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TailwindTraders.Mobile.Features.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Alert_Title_UnexpectedError {
            get {
                return ResourceManager.GetString("Alert_Title_UnexpectedError", resourceCulture);
            }
        }
        
        internal static string Alert_Message_InternetError {
            get {
                return ResourceManager.GetString("Alert_Message_InternetError", resourceCulture);
            }
        }
        
        internal static string Alert_OK_OKEllipsis {
            get {
                return ResourceManager.GetString("Alert_OK_OKEllipsis", resourceCulture);
            }
        }
        
        internal static string Snack_Message_InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("Snack_Message_InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        internal static string Snack_Message_InvalidAbsoluteURL {
            get {
                return ResourceManager.GetString("Snack_Message_InvalidAbsoluteURL", resourceCulture);
            }
        }
        
        internal static string Snack_Message_SettingsSaved {
            get {
                return ResourceManager.GetString("Snack_Message_SettingsSaved", resourceCulture);
            }
        }
        
        internal static string Alert_Message_DemoApp {
            get {
                return ResourceManager.GetString("Alert_Message_DemoApp", resourceCulture);
            }
        }
        
        internal static string Alert_OK {
            get {
                return ResourceManager.GetString("Alert_OK", resourceCulture);
            }
        }
        
        internal static string Alert_Title_FeatureNotAvailable {
            get {
                return ResourceManager.GetString("Alert_Title_FeatureNotAvailable", resourceCulture);
            }
        }
        
        internal static string Alert_Message_PermissionsNotGranted {
            get {
                return ResourceManager.GetString("Alert_Message_PermissionsNotGranted", resourceCulture);
            }
        }
        
        internal static string Alert_Message_NoCameraSupport {
            get {
                return ResourceManager.GetString("Alert_Message_NoCameraSupport", resourceCulture);
            }
        }
        
        internal static string Alert_Title_NoCameraSupport {
            get {
                return ResourceManager.GetString("Alert_Title_NoCameraSupport", resourceCulture);
            }
        }
        
        internal static string Alert_Title_PermissionsNotGranted {
            get {
                return ResourceManager.GetString("Alert_Title_PermissionsNotGranted", resourceCulture);
            }
        }
    }
}
