//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TailwindTraders.Mobile.Features.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TailwindTraders.Mobile.Features.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added to cart.
        /// </summary>
        internal static string Alert_Added_To_Cart {
            get {
                return ResourceManager.GetString("Alert_Added_To_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You reached one of the ends for this demo app..
        /// </summary>
        internal static string Alert_Message_DemoApp {
            get {
                return ResourceManager.GetString("Alert_Message_DemoApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was an error requesting data over Internet..
        /// </summary>
        internal static string Alert_Message_InternetError {
            get {
                return ResourceManager.GetString("Alert_Message_InternetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we couldn&apos;t find a camera on this device. Thanks in advance..
        /// </summary>
        internal static string Alert_Message_NoCameraSupport {
            get {
                return ResourceManager.GetString("Alert_Message_NoCameraSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to enter this page without permissions granted..
        /// </summary>
        internal static string Alert_Message_PermissionsNotGranted {
            get {
                return ResourceManager.GetString("Alert_Message_PermissionsNotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Alert_OK {
            get {
                return ResourceManager.GetString("Alert_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK....
        /// </summary>
        internal static string Alert_OK_OKEllipsis {
            get {
                return ResourceManager.GetString("Alert_OK_OKEllipsis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature not available.
        /// </summary>
        internal static string Alert_Title_FeatureNotAvailable {
            get {
                return ResourceManager.GetString("Alert_Title_FeatureNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a camera.
        /// </summary>
        internal static string Alert_Title_NoCameraSupport {
            get {
                return ResourceManager.GetString("Alert_Title_NoCameraSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions not granted.
        /// </summary>
        internal static string Alert_Title_PermissionsNotGranted {
            get {
                return ResourceManager.GetString("Alert_Title_PermissionsNotGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error.
        /// </summary>
        internal static string Alert_Title_UnexpectedError {
            get {
                return ResourceManager.GetString("Alert_Title_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, type a well-formed absolute URL..
        /// </summary>
        internal static string Snack_Message_InvalidAbsoluteURL {
            get {
                return ResourceManager.GetString("Snack_Message_InvalidAbsoluteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, type non-empty email and password..
        /// </summary>
        internal static string Snack_Message_InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("Snack_Message_InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved!.
        /// </summary>
        internal static string Snack_Message_SettingsSaved {
            get {
                return ResourceManager.GetString("Snack_Message_SettingsSaved", resourceCulture);
            }
        }
    }
}
