#!/bin/sh

cd ..

cd tensorflow/contrib/lite/tools/make
./download_dependencies.sh

cd ../../../../..
tensorflow/contrib/lite/tools/make/build_ios_universal_lib.sh 

mkdir -p lib/ios
cp tensorflow/tensorflow/contrib/lite/tools/make/gen/lib/libtensorflow-lite.a lib/ios/libtfliteextern.a
